# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn build
      - if: "github.event.release.prerelease"
        run: yarn publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - if: "github.event.release.prerelease"
        run: cd src/server/function/twikoo && yarn publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - if: "github.event.release.prerelease"
        run: cd src/server/vercel && yarn publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - if: "github.event.release.prerelease"
        run: cd src/server/self-hosted && yarn publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - if: "!github.event.release.prerelease"
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - if: "!github.event.release.prerelease"
        run: cd src/server/function/twikoo && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - if: "!github.event.release.prerelease"
        run: cd src/server/vercel && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - if: "!github.event.release.prerelease"
        run: cd src/server/self-hosted && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
